FROM amazoncorretto:17-alpine-jdk
MAINTAINER alexeymoskvinov
COPY target/account-service-0.0.1-SNAPSHOT.jar account-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/account-service-0.0.1-SNAPSHOT.jar"]


